{% set name = "ultralytics-thop" %}
{% set version = "2.1.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0ec2df8ebd3db35795e1f80cdc8bce6734446dbe989bca1b0c89396353f0f08c

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<38]

requirements:
  host:
    - python
    - setuptools >=70.0.0
    - wheel
    - pip
  run:
    - python
    - numpy
    - pytorch

test:
  source_files:
    - tests
  imports:
    - thop
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv tests
  requires:
    - pip
    - pytest
  
about:
  home: https://www.ultralytics.com/
  summary: Ultralytics THOP package for fast computation of PyTorch model FLOPs and parameters.
  description: | 
    THOP offers an intuitive API designed to profile PyTorch models by calculating the total number of MACs and parameters. 
    This functionality is vital for assessing the computational efficiency and memory footprint of deep learning models,
    helping developers optimize performance for deployment, especially on edge devices.
    Understanding these metrics is key to selecting the right model architecture, a topic explored in our model comparison pages.
  license: AGPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  dev_url: https://github.com/ultralytics/thop
  doc_url: https://docs.ultralytics.com

extra:
  skip-lints:
    - cbc_dep_in_run_missing_from_host